name: input_country
description: Countries (ISO-3166), Currencies (ISO-4217), Languages (ISO-639) with choosers (DropdownButton) and flag images
homepage: https://github.com/djarjo/input_country
version: 2.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  pedantic: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/flags/
